input {
  tcp {
    port => 5000      # Logstash mở cổng 5000 để lắng nghe log từ Spring Boot gửi tới
    codec => json     # Log nhận vào có định dạng JSON, Logstash sẽ tự parse
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]       # Địa chỉ Elasticsearch trong Docker network
    index => "backend-service-%{+YYYY.MM.dd}"   # Tên nhóm log, tạo mới theo từng ngày
  }
}